"""fixed read column in notifications table

Revision ID: 5f3dd32c45cc
Revises: 1545e348c3a4
Create Date: 2026-07-13 10:34:10.345703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f3dd32c45cc'
down_revision: Union[str, Sequence[str], None] = '1545e348c3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
